### ISSUE TITLE
Viewpoint for OML

### ISSUE THREAD

**Issue by dyates** [JPL-IMCE/gov.nasa.jpl.imce.oml#42] opened 2017-06-13 20:32 UTC
Define graphical viewpoint for OML

**Comment by NicolasRouquette** [comment] 2017-08-24 17:07
Please fix this:

Caused by: java.lang.NullPointerException
	at gov.nasa.jpl.imce.oml.viewpoint.DiagramUtil.getContainedEntityStructuredDataProperties(DiagramUtil.java:35)

**Comment by dyates** [comment] 2017-08-24 17:07
# Fix EntityUniversial/Existential Restriction Axioms.  Source/Target should be reversed;
    # Add restricted relationship name on label
    # Change to open arrowhead
# Fix runtime errors; Make model (un)synchronized?

**Comment by NicolasRouquette** [comment] 2017-08-29 16:15
The Travis-CI job failed: https://travis-ci.org/JPL-IMCE/gov.nasa.jpl.imce.oml/builds/269360896

```
[ERROR] Failed to resolve target definition /root/sources/releng/gov.nasa.jpl.imce.oml.target/gov.nasa.jpl.imce.oml.target.target: Could not find "org.eclipse.sirius.specifier.ide.ui.aql.source.feature.group/4.1.3.201701271256" in the repositories of the current location -> [Help 1]
org.apache.maven.MavenExecutionException: Failed to resolve target definition /root/sources/releng/gov.nasa.jpl.imce.oml.target/gov.nasa.jpl.imce.oml.target.target: Could not find "org.eclipse.sirius.specifier.ide.ui.aql.source.feature.group/4.1.3.201701271256" in the repositories of the current location
```

It seems that the repository has moved.
A while ago, we used this repo:
http://www.obeo.fr/download/release/designer/9.1/community/latest/repository

However, this location is no longer accessible.
The Sirus-related repos seem to have moved in part here:
http://download.eclipse.org/sirius/updates/releases/
It is unclear where is the repo for the `fr.obeo.dsl.designer.ce.*" features.

**Comment by NicolasRouquette** [comment] 2017-08-29 16:47
Suggestion:

1) `/gov.nasa.jpl.imce.oml.target/gov.nasa.jpl.imce.oml.target.target`, 

change the repository `http://www.obeo.fr/download/release/designer/9.1/community/latest/repository` to
one of `http://download.eclipse.org/sirius/updates/releases/` for the appropriate versions.
(for now, it seems that we need the sirius 4.1 release)

2) Remove the features `fr.obeo.dsl.designer.ce.feature.feature.group` and `fr.obeo.dsl.designer.ce.feature.source.feature.group`

**Comment by NicolasRouquette** [comment] 2017-08-29 17:36
I used this "P2 Browser" application:
https://github.com/ifedorenko/p2-browser
(`git clone`; then do `mvn clean package`; then start the application from `com.ifedorenko.p2browser.rcp/target/products/com.ifedorenko.p2browser.rcp/`)

With P2 Browser, we can see that in fact the obeo repo is available;
however, version 4.1.3 of the `org.eclipse.sirus` features are no longer available;
instead the repo has version 4.1.5

So, the suggestion still stands; it's preferable to pick a version of Sirius instead of relying on the volatile contents of the "latest" obeo repo.

**Comment by NicolasRouquette** [comment] 2017-09-21 04:49
Resolved in https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml/releases/tag/0.8.0.1

**Closed by NicolasRouquette** 2017-09-21 04:49 UTC
